version: "3.9"
name: instaquizwebapp
services:
  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: webserver
    container_name: instaquiz-webserver
    volumes:
      - './app:/var/www/html'
      - './composer:/usr/local/bin/composer:ro' # mount composer binary from composer service
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: db
    container_name: instaquiz-database
    restart: always
    environment:
      - MYSQL_DATABASE=instaquiz
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=310adminpw 
      - MYSQL_ROOT_PASSWORD=310adminpw 
    volumes:
      - './db:/docker-entrypoint-initdb.d' # this is how we persist a sql db even when container stops
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: instaquiz_phpmyadmin
    #restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  composer:
    image: composer:latest
    container_name: instaquiz-composer
    volumes:
      - './app:/app'
      - './composer:/tmp'
    working_dir: /app