version: "3"
services:
  webserver:
    image: php:apache
    container_name: instaquiz-webserver
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
  app:
    container_name: instaquiz-application
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app  
  db:
    image: mysql:latest
    container_name: instaquiz-database
    restart: always
    environment:
      - MYSQL_DATABASE=instaquiz
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=310adminpw # this should live in a env var
      - MYSQL_ROOT_PASSWORD=310adminpw # this should live in a env var
    volumes:
      - './db:/docker-entrypoint-initdb.d' # this is how we persist a sql db even when container stops
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: instaquiz_dbAdmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306