name: Docker CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      working-directory: './InstaQuiz (WebApp)'
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
    - uses: actions/checkout@v3
    - name: update apt-get
      run: sudo apt-get update
    - name: get key for docker ubuntu
      run: sudo apt-get install ca-certificates curl gnupg lsb-release
    - name: save keyring
      run: sudo mkdir -m 0755 -p /etc/apt/keyrings
    - name: download docker
      run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - name: download latest release
      run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: update apt-get again
      run: sudo apt-get update
    - name: install latest docker-compose
      run: sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - name: Build the Docker images
      run: docker-compose build
    - name: Compose Docker Containers
      run: docker-compose up
    - name: Install phpunit
      run: docker exec instaquiz-webserver composer require --dev phpunit/phpunit
    - name: Run Test
      run: docker exec instaquiz-webserver ./vendor/bin/phpunit ./tests/Test.php
